### PR TITLE
Update Dutch airspace to version EH1904A

### PR DESCRIPTION
**Pull request by roeles**
This should be merged together with this pull request:
https://github.com/XCSoar/xcsoar-data-content/pull/76

### CODE REVIEW

**Comment by roeles** [comment]
The referenced pull request has been merged, so CI should now pass

**Comment by hor63** [comment]
The new files is commited to the repository in GitHub, that is true.
However [XCSoar Download](http://download.xcsoar.org/airspaces/) is not yet synchronized. The new file has not shown up yet.
I will merge this pull request once the new file is available.

**Comment by roeles** [comment]
@hor63 Thanks the reply! I understand, thanks.

**Comment by lordfolken** [comment]
Merging this, as the failing URL is now USA.

**Pull request merged**
