### PR TITLE
updated openAIP hotspot URI

### PR DESCRIPTION
**Pull request by reskume**

### CODE REVIEW

**Comment by Turbo87** [comment]
hi @reskume, could you rebase on the current `master`? our CI pipeline had a small issue which I just resolved in #59

**Comment by reskume** [comment]
hi @Turbo87 , sorry being late. didn't see the notification. should I rebase and create a pull request again?

**Comment by Turbo87** [comment]
Should be enough to rebase and force-push to the same branch. The PR will update automatically then.

**Comment by Turbo87** [comment]
seems to work fine now, thanks!

**Comment by reskume** [comment]
Perfect, no problem. You are welcome.

**Pull request merged**
