### PR TITLE
Updated French airspace links

### LINKED ISSUE #48: French Airspace failing with 404
The nightly tests revealed that the French Airspace link has been failing with HTTP 404 for a few days now

### PR DESCRIPTION
**Pull request by clementallen**
fixes #48

### CODE REVIEW

**Comment by clementallen** [comment]
Tests are passing locally

**Comment by Turbo87** [comment]
@clementallen could you remove that unrelated merge commit from the PR?

**Comment by Turbo87** [comment]
thanks!

**Comment by lordfolken** [comment]
This is an old file. http://www.ffvvespaceaerien.org/?page_id=412 links to http://s289271336.onlinehome.fr/dossiers_ffvv/files/160222__AIRSPACE_FRANCE_TXT_1602a.txt

I wrote them a mail for the failing "latest" url. for now lets link to that file.

**Pull request merged**
