### PR TITLE
Update Canadian Airspace Link

### PR DESCRIPTION
**Pull request by ventus99**
Added from http://download.xcsoar.org/airspaces/Canada_Airspace.txt effective Nov 5, 2020

https://soaringtasks.com/canairspace/

### CODE REVIEW

**Comment by rawtaz** [comment]
I guess we'll have to wait for the 5th of november before merging this.

**Comment by ventus99** [comment]
> I guess we'll have to wait for the 5th of november before merging this.

Ya.  Is it possible to schedule a merge?

**Comment by rawtaz** [comment]
Sure, I'll add it to my calendar ;-)

**Review by rawtaz — APPROVED** [review]
One day late by me, but better late than never! :D

**Pull request merged**
