### PR TITLE
French airspace: update

### PR DESCRIPTION
**Pull request by mlep**

### CODE REVIEW

**Comment by rawtaz** [comment]
Looks like the date should be 2021-05-20 instead of 2021-05-26 (looking in the file's header)?

**Comment by mlep** [comment]
Date changed to the one mentioned in the file.
FYI: there is in fact two dates for this file: the one of the French Soaring Association (2021-05-20) and the one of the publication of the corrected version (today).

**Comment by rawtaz** [comment]
Yeah. I think the routine is that we go by the date in which the data/file says it's valid from, even if we notice or it's published later.

**Review by rawtaz — APPROVED** [review]
LGTM

**Pull request merged**
