### PR TITLE
Airspace austria

### PR DESCRIPTION
**Pull request by Surkes**
Removed the outdated airspace uris for austria and added the current airspace file from austrocontrol eaip.

[Source](https://www.austrocontrol.at/piloten/vor_dem_flug/aim_produkte/luftraumstruktur)

### CODE REVIEW

**Comment by rawtaz** [comment]
@Surkes Thanks! The automated checks are failing, but that's not because of your changes.

I am however wondering, shouldn't you use the latest file instead, which is https://www.austrocontrol.at/jart/prj3/ac/data/dokumente/austria_acg_airspaces_2020-05-21_xcsoar_2020-04-02_1304955.txt from what I can tell?

Also, can you squash those two commits into one, and force-push to your branch to update this PR? The two commits are a bit funky and it only needs to be one. Let us know if you need help. If you do update the URL, please squash and push afterwards.

**Comment by Surkes** [comment]
Yeah, I saw that i fixed a typo with the same commit. 
I will merge that to one commit.

The newest one is valid from 2020-05-21.
I will update to the newest one when it's time to update. Ok? :-)

**Comment by rawtaz** [comment]
> The newest one is valid from 2020-05-21. I will update to the newest one when it's time to update.

Ah, I see! Sure, that's the right thing to do :)

Please *squash* it to one commit, instead of *merge* it to one commit. You can do that using `git rebase -i HEAD^^` and changing "pick" to "s" for the commit you want to meld into the previous one. Then `git push -f`.

**Comment by rawtaz** [comment]
That's the first time I saw a PR being pushed to have 0 commits :D

You can probably reopen it using the buttons here on GitHub and then push commits anew.

**Comment by Surkes** [comment]
Changed to one commit and reopened.

> That's the first time I saw a PR being pushed to have 0 commits :D
I was fighting a little bit with git ;-)

**Comment by rawtaz** [comment]
Due to the other failure Travis detects (not due to changes in this PR) I cannot merge this yet. Looking into that. Worst case we'll have to rebase this commit again once the other problem is fixed, but we'll see.

**Comment by Surkes** [comment]
Ok.
Nevertheless, thank you for your fast response on my PR. :-)

**Pull request merged**
