### PR TITLE
Use JSON as source format

### PR DESCRIPTION
**Pull request by Turbo87**
... and compile to the XCSoar plaintext format when necessary

### CODE REVIEW

**Comment by Turbo87** [comment]
@lordfolken @TobiasLohner feedback welcome

**Comment by lordfolken** [comment]
I'm fine with json format. This is more easily parsable. Ultimately it should be the goal for XCSoar to parse the json format aswell. XCSoar should also be able to download the individual files sepereatly from each other. It also should only do this when one of the files has actually changed. (Via checksum/data)

We should also think about adding additional data fields. For example the corner coordinates for the airspace and maps files, to enable auto downloads of maps in xcsoar.

**Comment by TobiasLohner** [comment]
This might allow us to add other data fields required by SkyLines to
import airspace files, doesn't it. So we could finally use one single
repository for both projects.


On 24.02.2015 12:15, Tobias Bieniek wrote:
> ... and compile to the XCSoar plaintext format when necessary
> 
> ------------------------------------------------------------------------
> 
> 
>         You can view, comment on, or merge this pull request online at:
> 
>   https://github.com/XCSoar/xcsoar-data-repository/pull/19
> 
> 
>         Commit Summary
> 
>   * Converted repository to JSON
>   * Split repository.json up into multiple files
> 
> 
>         File Changes
> 
>   * *M* .gitignore
>     <https://github.com/XCSoar/xcsoar-data-repository/pull/19/files#diff-0>
>     (1)
>   * *M* .travis.yml
>     <https://github.com/XCSoar/xcsoar-data-repository/pull/19/files#diff-1>
>     (1)
>   * *A* bin/convert.js
>     <https://github.com/XCSoar/xcsoar-data-repository/pull/19/files#diff-2>
>     (24)
>   * *A* data/airspace.json
>     <https://github.com/XCSoar/xcsoar-data-repository/pull/19/files#diff-3>
>     (180)
>   * *A* data/flarmnet.json
>     <https://github.com/XCSoar/xcsoar-data-repository/pull/19/files#diff-4>
>     (9)
>   * *A* data/gliding-hotspots.json
>     <https://github.com/XCSoar/xcsoar-data-repository/pull/19/files#diff-5>
>     (9)
>   * *A* data/index.js
>     <https://github.com/XCSoar/xcsoar-data-repository/pull/19/files#diff-6>
>     (9)
>   * *A* data/maps.json
>     <https://github.com/XCSoar/xcsoar-data-repository/pull/19/files#diff-7>
>     (516)
>   * *A* data/openaip.json
>     <https://github.com/XCSoar/xcsoar-data-repository/pull/19/files#diff-8>
>     (9)
>   * *A* data/travel-by-glider.json
>     <https://github.com/XCSoar/xcsoar-data-repository/pull/19/files#diff-9>
>     (35)
>   * *A* data/waypoints.json
>     <https://github.com/XCSoar/xcsoar-data-repository/pull/19/files#diff-10>
>     (40)
>   * *A* index.js
>     <https://github.com/XCSoar/xcsoar-data-repository/pull/19/files#diff-11>
>     (1)
>   * *M* package.json
>     <https://github.com/XCSoar/xcsoar-data-repository/pull/19/files#diff-12>
>     (1)
>   * *D* repository
>     <https://github.com/XCSoar/xcsoar-data-repository/pull/19/files#diff-13>
>     (668)
>   * *M* test.js
>     <https://github.com/XCSoar/xcsoar-data-repository/pull/19/files#diff-14>
>     (60)
> 
> 
>         Patch Links:
> 
>   * https://github.com/XCSoar/xcsoar-data-repository/pull/19.patch
>   * https://github.com/XCSoar/xcsoar-data-repository/pull/19.diff
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/XCSoar/xcsoar-data-repository/pull/19>.
> 

-- 
Die Wettergespräche [kommen] nicht von Langweile, sondern weil der
Mensch immer eine starke fortdauernde Empfindung mit Worten äußern und
geben will - wäre Krieg, so gäb's Kriegsgespräche.
		-- Jean Paul

**Comment by Turbo87** [comment]
I take it that there are no objections then.

**Pull request merged**
